[build]
builder = "nixpacks"
buildCommand = "npm ci && npm run build"

[deploy]
startCommand = "npx drizzle-kit push && npm run start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 300

[nixpacks]
nixPkgs = ["nodejs_20"]

[build.env]
NPM_CONFIG_PRODUCTION = "false"
