/**
 * Public OpenAPI contract for the external institutional intelligence API.
 *
 * Keep this file limited to public contract information. In particular, do
 * not add database table names, internal URLs, credentials, or stack details.
 */

const ref = (name: string) => ({ $ref: `#/components/schemas/${name}` });
const parameterRef = (name: string) => ({ $ref: `#/components/parameters/${name}` });
const responseRef = (name: string) => ({ $ref: `#/components/responses/${name}` });

const dataResponse = (schema: string) => ({
  description: "Successful response.",
  headers: {
    "X-Request-Id": { $ref: "#/components/headers/X-Request-Id" },
    "X-RateLimit-Limit": { $ref: "#/components/headers/X-RateLimit-Limit" },
    "X-RateLimit-Remaining": { $ref: "#/components/headers/X-RateLimit-Remaining" },
    "X-RateLimit-Reset": { $ref: "#/components/headers/X-RateLimit-Reset" },
  },
  content: {
    "application/json": {
      schema: {
        allOf: [
          { $ref: "#/components/schemas/SuccessEnvelope" },
          {
            type: "object",
            properties: { data: ref(schema) },
          },
        ],
      },
    },
  },
});

const authenticated = [{ bearerAuth: ["institutional:read"] }];

export const institutionalApiV1OpenApi = {
  openapi: "3.1.0",
  jsonSchemaDialect: "https://json-schema.org/draft/2020-12/schema",
  info: {
    title: "StockMetrics Institutional Intelligence API",
    version: "1.0.0",
    summary: "Quarterly institutional ownership analytics.",
    description: [
      "External, read-only analytics derived from SEC Form 13F reported holdings.",
      "",
      "## Authentication",
      "Institutional data endpoints use `Authorization: Bearer <api-key>`. API keys are separate from StockMetrics application sessions and must have the `institutional:read` scope. The public API never accepts a browser session cookie as authentication.",
      "",
      "Keys use `sm_live_` or `sm_test_` prefixes. Treat a raw key like a password; it is shown only when created. Never put a key in a URL or source-control repository.",
      "",
      "## Rate limits",
      "Limits are assigned by API client and tier. Successful and rejected requests expose `X-RateLimit-Limit`, `X-RateLimit-Remaining`, and Unix-seconds `X-RateLimit-Reset`. When a limit is exceeded, the API returns HTTP 429, a standard error envelope, and `Retry-After`.",
      "",
      "## Query conventions",
      "`quarter` is `latest` or an explicit quarter such as `2026-Q1`. Position types are independent: `COMMON_EQUITY` is the default; `PUT` and `CALL` select reported option positions rather than being merged into common equity. Ranking `limit` is 1–100 and `offset` is zero-based.",
      "",
      "## Form 13F limitations",
      "13F information is delayed, reflects reportable holdings as filed by institutions, and is not a real-time position feed. Filing dates, amendments, mapping gaps, unavailable values, and quarter-to-quarter comparability can affect results. Null values mean the source value is unavailable; they are not zero.",
      "",
      "## Example: top institutional accumulation candidates",
      "The following examples request the first page for the latest quarter:",
      "```bash",
      "curl -H 'Authorization: Bearer sm_live_REDACTED' 'https://your-app.example/api/v1/institutional/trends/accumulation?limit=10&sortBy=netHolderIncrease&sortDirection=desc'",
      "```",
      "```js",
      "const response = await fetch('/api/v1/institutional/trends/accumulation?limit=10&sortBy=netHolderIncrease&sortDirection=desc', { headers: { Authorization: `Bearer ${apiKey}` } });",
      "const { data, meta } = await response.json();",
      "```",
      "```ts",
      "type AccumulationResponse = { data: InstitutionalRanking; meta: ApiMeta };",
      "const response = await fetch('/api/v1/institutional/trends/accumulation?limit=10', { headers: { Authorization: `Bearer ${apiKey}` } });",
      "if (!response.ok) throw new Error((await response.json()).error.message);",
      "const result: AccumulationResponse = await response.json();",
      "```",
    ].join("\n"),
    contact: {
      name: "StockMetrics API",
    },
  },
  servers: [
    {
      url: "/",
      description: "Same-origin application host",
    },
  ],
  tags: [
    { name: "Health", description: "Liveness information." },
    { name: "Funds", description: "Institutional fund portfolio analytics." },
    { name: "Stocks", description: "Institutional ownership analytics for a symbol." },
    { name: "Rankings", description: "Cross-fund institutional activity rankings." },
    { name: "Rotation", description: "Sector, industry, and theme rotation analytics." },
  ],
  paths: {
    "/api/v1/openapi.json": {
      get: {
        tags: ["Health"],
        operationId: "getInstitutionalApiOpenApi",
        summary: "Get the machine-readable API contract",
        description: "Returns this public OpenAPI document. It contains no credentials or private implementation details.",
        security: [],
        responses: {
          "200": {
            description: "OpenAPI 3.1 document.",
            content: {
              "application/json": {
                schema: { type: "object" },
              },
            },
          },
        },
      },
    },
    "/api/v1/health": {
      get: {
        tags: ["Health"],
        operationId: "getApiHealth",
        summary: "Check API availability",
        description: "A liveness endpoint. It does not expose institutional data.",
        security: [],
        responses: {
          "200": dataResponse("Health"),
        },
      },
    },
    "/api/v1/institutional/funds/{managerId}": {
      get: {
        tags: ["Funds"],
        operationId: "getFundInstitutionalAnalytics",
        summary: "Get fund institutional analytics",
        description: "Returns the selected fund's reported portfolio, allocations, and quarter-over-quarter position changes.",
        security: authenticated,
        parameters: [
          parameterRef("ManagerId"),
          parameterRef("Quarter"),
          parameterRef("PositionType"),
          parameterRef("TopN"),
        ],
        responses: {
          "200": dataResponse("FundAnalytics"),
          "400": responseRef("BadRequest"),
          "401": responseRef("Unauthorized"),
          "403": responseRef("Forbidden"),
          "404": responseRef("Unavailable"),
          "429": responseRef("RateLimited"),
          "500": responseRef("ServerError"),
        },
      },
    },
    "/api/v1/institutional/funds/{managerId}/analytics": {
      get: {
        tags: ["Funds"],
        operationId: "getFundInstitutionalAnalyticsDetail",
        summary: "Get detailed fund institutional analytics",
        description: "Alias of the fund analytics resource with the explicit `/analytics` suffix.",
        security: authenticated,
        parameters: [
          parameterRef("ManagerId"),
          parameterRef("Quarter"),
          parameterRef("PositionType"),
          parameterRef("TopN"),
        ],
        responses: {
          "200": dataResponse("FundAnalytics"),
          "400": responseRef("BadRequest"),
          "401": responseRef("Unauthorized"),
          "403": responseRef("Forbidden"),
          "404": responseRef("Unavailable"),
          "429": responseRef("RateLimited"),
          "500": responseRef("ServerError"),
        },
      },
    },
    "/api/v1/institutional/stocks/{symbol}": {
      get: {
        tags: ["Stocks"],
        operationId: "getStockInstitutionalAnalytics",
        summary: "Get institutional analytics for a stock",
        security: authenticated,
        parameters: [
          parameterRef("Symbol"),
          parameterRef("Quarter"),
          parameterRef("PositionType"),
          parameterRef("Cohort"),
          parameterRef("TopN"),
        ],
        responses: {
          "200": dataResponse("StockAnalytics"),
          "400": responseRef("BadRequest"),
          "401": responseRef("Unauthorized"),
          "403": responseRef("Forbidden"),
          "404": responseRef("Unavailable"),
          "429": responseRef("RateLimited"),
          "500": responseRef("ServerError"),
        },
      },
    },
    "/api/v1/institutional/stocks/{symbol}/trend": {
      get: {
        tags: ["Stocks"],
        operationId: "getStockInstitutionalTrend",
        summary: "Get a stock's multi-quarter institutional trend",
        security: authenticated,
        parameters: [
          parameterRef("Symbol"),
          parameterRef("Quarter"),
          parameterRef("PositionType"),
          parameterRef("Cohort"),
          parameterRef("HistoryQuarters"),
        ],
        responses: {
          "200": dataResponse("StockTrend"),
          "400": responseRef("BadRequest"),
          "401": responseRef("Unauthorized"),
          "403": responseRef("Forbidden"),
          "404": responseRef("Unavailable"),
          "429": responseRef("RateLimited"),
          "500": responseRef("ServerError"),
        },
      },
    },
    "/api/v1/institutional/trends/accumulation": {
      get: {
        tags: ["Rankings"],
        operationId: "getInstitutionalAccumulationRanking",
        summary: "Rank stocks by institutional accumulation",
        description: "Returns the top candidates by the selected accumulation activity metrics. This is descriptive ownership analytics, not a trading recommendation.",
        security: authenticated,
        parameters: [
          parameterRef("RankingQuarter"),
          parameterRef("PositionType"),
          parameterRef("Cohort"),
          parameterRef("Sector"),
          parameterRef("Industry"),
          parameterRef("Theme"),
          parameterRef("MarketCapMin"),
          parameterRef("MarketCapMax"),
          parameterRef("MinManagers"),
          parameterRef("MinReportedValue"),
          parameterRef("SortBy"),
          parameterRef("SortDirection"),
          parameterRef("Limit"),
          parameterRef("Offset"),
        ],
        "x-codeSamples": [
          {
            lang: "curl",
            label: "curl",
            source: "curl -H 'Authorization: Bearer sm_live_REDACTED' 'https://your-app.example/api/v1/institutional/trends/accumulation?limit=10&sortBy=netHolderIncrease&sortDirection=desc'",
          },
          {
            lang: "JavaScript",
            label: "JavaScript fetch",
            source: "const response = await fetch('/api/v1/institutional/trends/accumulation?limit=10', { headers: { Authorization: `Bearer ${apiKey}` } });\nconst result = await response.json();",
          },
          {
            lang: "TypeScript",
            label: "TypeScript",
            source: "const response = await fetch('/api/v1/institutional/trends/accumulation?limit=10', { headers: { Authorization: `Bearer ${apiKey}` } });\nif (!response.ok) throw new Error((await response.json()).error.message);\nconst result: SuccessEnvelope<InstitutionalRanking> = await response.json();",
          },
        ],
        responses: {
          "200": dataResponse("InstitutionalRanking"),
          "400": responseRef("BadRequest"),
          "401": responseRef("Unauthorized"),
          "403": responseRef("Forbidden"),
          "429": responseRef("RateLimited"),
          "500": responseRef("ServerError"),
        },
      },
    },
    "/api/v1/institutional/trends/reduction": {
      get: {
        tags: ["Rankings"],
        operationId: "getInstitutionalReductionRanking",
        summary: "Rank stocks by institutional reduction",
        security: authenticated,
        parameters: [{ $ref: "#/components/parameters/RankingQuarter" }, parameterRef("PositionType"), parameterRef("Cohort"), parameterRef("Sector"), parameterRef("Industry"), parameterRef("Theme"), parameterRef("MarketCapMin"), parameterRef("MarketCapMax"), parameterRef("MinManagers"), parameterRef("MinReportedValue"), parameterRef("SortBy"), parameterRef("SortDirection"), parameterRef("Limit"), parameterRef("Offset")],
        responses: {
          "200": dataResponse("InstitutionalRanking"),
          "400": responseRef("BadRequest"),
          "401": responseRef("Unauthorized"),
          "403": responseRef("Forbidden"),
          "429": responseRef("RateLimited"),
          "500": responseRef("ServerError"),
        },
      },
    },
    "/api/v1/institutional/trends/new-positions": {
      get: {
        tags: ["Rankings"],
        operationId: "getNewInstitutionalPositions",
        summary: "Rank stocks by newly reported positions",
        security: authenticated,
        parameters: [{ $ref: "#/components/parameters/RankingQuarter" }, parameterRef("PositionType"), parameterRef("Cohort"), parameterRef("Sector"), parameterRef("Industry"), parameterRef("Theme"), parameterRef("MarketCapMin"), parameterRef("MarketCapMax"), parameterRef("MinManagers"), parameterRef("MinReportedValue"), parameterRef("SortBy"), parameterRef("SortDirection"), parameterRef("Limit"), parameterRef("Offset")],
        responses: {
          "200": dataResponse("InstitutionalRanking"),
          "400": responseRef("BadRequest"),
          "401": responseRef("Unauthorized"),
          "403": responseRef("Forbidden"),
          "429": responseRef("RateLimited"),
          "500": responseRef("ServerError"),
        },
      },
    },
    "/api/v1/institutional/trends/exits": {
      get: {
        tags: ["Rankings"],
        operationId: "getInstitutionalExits",
        summary: "Rank stocks by no-longer-reported positions",
        security: authenticated,
        parameters: [{ $ref: "#/components/parameters/RankingQuarter" }, parameterRef("PositionType"), parameterRef("Cohort"), parameterRef("Sector"), parameterRef("Industry"), parameterRef("Theme"), parameterRef("MarketCapMin"), parameterRef("MarketCapMax"), parameterRef("MinManagers"), parameterRef("MinReportedValue"), parameterRef("SortBy"), parameterRef("SortDirection"), parameterRef("Limit"), parameterRef("Offset")],
        responses: {
          "200": dataResponse("InstitutionalRanking"),
          "400": responseRef("BadRequest"),
          "401": responseRef("Unauthorized"),
          "403": responseRef("Forbidden"),
          "429": responseRef("RateLimited"),
          "500": responseRef("ServerError"),
        },
      },
    },
    "/api/v1/institutional/rotation/sectors": {
      get: {
        tags: ["Rotation"],
        operationId: "getSectorRotation",
        summary: "Get sector rotation analytics",
        security: authenticated,
        parameters: [parameterRef("Quarter"), parameterRef("PositionType"), parameterRef("Cohort")],
        responses: {
          "200": dataResponse("Rotation"),
          "400": responseRef("BadRequest"),
          "401": responseRef("Unauthorized"),
          "403": responseRef("Forbidden"),
          "429": responseRef("RateLimited"),
          "500": responseRef("ServerError"),
        },
      },
    },
    "/api/v1/institutional/rotation/industries": {
      get: {
        tags: ["Rotation"],
        operationId: "getIndustryRotation",
        summary: "Get industry rotation analytics",
        security: authenticated,
        parameters: [parameterRef("Quarter"), parameterRef("PositionType"), parameterRef("Cohort")],
        responses: {
          "200": dataResponse("Rotation"),
          "400": responseRef("BadRequest"),
          "401": responseRef("Unauthorized"),
          "403": responseRef("Forbidden"),
          "429": responseRef("RateLimited"),
          "500": responseRef("ServerError"),
        },
      },
    },
    "/api/v1/institutional/rotation/themes": {
      get: {
        tags: ["Rotation"],
        operationId: "getThemeRotation",
        summary: "Get theme rotation analytics",
        security: authenticated,
        parameters: [parameterRef("Quarter"), parameterRef("PositionType"), parameterRef("Cohort")],
        responses: {
          "200": dataResponse("Rotation"),
          "400": responseRef("BadRequest"),
          "401": responseRef("Unauthorized"),
          "403": responseRef("Forbidden"),
          "429": responseRef("RateLimited"),
          "500": responseRef("ServerError"),
        },
      },
    },
  },
  components: {
    securitySchemes: {
      bearerAuth: {
        type: "http",
        scheme: "bearer",
        bearerFormat: "StockMetrics API key",
        description: "Use a dedicated API key in `Authorization: Bearer <api-key>`. Do not use an application-session cookie.",
        "x-scopes": {
          "institutional:read": "Read institutional Form 13F analytics.",
          "multibagger:read": "Reserved for a future API surface.",
          "fundamentals:read": "Reserved for a future API surface.",
          "research:read": "Reserved for a future API surface.",
        },
      },
    },
    headers: {
      "X-Request-Id": {
        description: "Request correlation identifier.",
        schema: { type: "string" },
      },
      "X-RateLimit-Limit": {
        description: "Maximum requests permitted in the current client window.",
        schema: { type: "integer", minimum: 1 },
      },
      "X-RateLimit-Remaining": {
        description: "Requests remaining in the current client window.",
        schema: { type: "integer", minimum: 0 },
      },
      "X-RateLimit-Reset": {
        description: "Unix timestamp when the current client window resets.",
        schema: { type: "integer", minimum: 0 },
      },
      "Retry-After": {
        description: "Seconds to wait before retrying a rate-limited request.",
        schema: { type: "integer", minimum: 1 },
      },
    },
    parameters: {
      ManagerId: {
        name: "managerId",
        in: "path",
        required: true,
        description: "SEC filer CIK, supplied as 1–10 digits and normalized by the service.",
        schema: { type: "string", pattern: "^\\d{1,10}$", example: "1234" },
      },
      Symbol: {
        name: "symbol",
        in: "path",
        required: true,
        description: "Ticker symbol, 1–10 uppercase letters, digits, periods, or hyphens.",
        schema: { type: "string", pattern: "^[A-Z][A-Z0-9.-]{0,9}$", example: "AAPL" },
      },
      Quarter: {
        name: "quarter",
        in: "query",
        required: false,
        description: "Quarter selector. Use `latest` or an explicit `YYYY-Q1` through `YYYY-Q4` value.",
        schema: { type: "string", pattern: "^(latest|\\d{4}-Q[1-4])$", default: "latest", example: "latest" },
      },
      RankingQuarter: {
        name: "quarter",
        in: "query",
        required: false,
        description: "Quarter selector. Use `latest` or an explicit `YYYY-Q1` through `YYYY-Q4` value.",
        schema: { type: "string", pattern: "^(latest|\\d{4}-Q[1-4])$", default: "latest", example: "2026-Q1" },
      },
      PositionType: {
        name: "positionType",
        in: "query",
        required: false,
        description: "Reported position category. `COMMON_EQUITY` is the default; `PUT` and `CALL` are queried independently.",
        schema: { type: "string", enum: ["COMMON_EQUITY", "PUT", "CALL"], default: "COMMON_EQUITY" },
      },
      Cohort: {
        name: "cohort",
        in: "query",
        required: false,
        description: "Optional curated manager cohort filter.",
        schema: {
          type: "string",
          enum: ["hedge_fund", "pension", "sovereign", "endowment", "asset_manager", "quantitative", "technology_specialist", "healthcare_specialist", "concentrated", "broad_diversified"],
        },
      },
      TopN: {
        name: "topN",
        in: "query",
        required: false,
        description: "Maximum number of largest-holder or largest-change rows in the response.",
        schema: { type: "integer", minimum: 1, maximum: 100, default: 20 },
      },
      HistoryQuarters: {
        name: "historyQuarters",
        in: "query",
        required: false,
        description: "Number of consecutive quarters to return.",
        schema: { type: "integer", minimum: 1, maximum: 8, default: 8 },
      },
      Sector: {
        name: "sector",
        in: "query",
        required: false,
        schema: { type: "string", minLength: 1, maxLength: 100 },
      },
      Industry: {
        name: "industry",
        in: "query",
        required: false,
        schema: { type: "string", minLength: 1, maxLength: 100 },
      },
      Theme: {
        name: "theme",
        in: "query",
        required: false,
        schema: { type: "string", minLength: 1, maxLength: 100 },
      },
      MarketCapMin: {
        name: "marketCapMin",
        in: "query",
        required: false,
        schema: { type: "integer", minimum: 0 },
      },
      MarketCapMax: {
        name: "marketCapMax",
        in: "query",
        required: false,
        schema: { type: "integer", minimum: 0 },
      },
      MinManagers: {
        name: "minManagers",
        in: "query",
        required: false,
        schema: { type: "integer", minimum: 1, maximum: 10000 },
      },
      MinReportedValue: {
        name: "minReportedValue",
        in: "query",
        required: false,
        schema: { type: "integer", minimum: 0 },
      },
      SortBy: {
        name: "sortBy",
        in: "query",
        required: false,
        description: "Safe ranking sort field.",
        schema: {
          type: "string",
          enum: ["netHolderIncrease", "newHolderCount", "increasedHolderCount", "aggregateShareIncreasePct", "aggregateShareIncrease", "reportedValue"],
          default: "netHolderIncrease",
        },
      },
      SortDirection: {
        name: "sortDirection",
        in: "query",
        required: false,
        schema: { type: "string", enum: ["asc", "desc"], default: "desc" },
      },
      Limit: {
        name: "limit",
        in: "query",
        required: false,
        description: "Number of ranking items to return.",
        schema: { type: "integer", minimum: 1, maximum: 100, default: 50 },
      },
      Offset: {
        name: "offset",
        in: "query",
        required: false,
        description: "Zero-based number of ranking items to skip.",
        schema: { type: "integer", minimum: 0, maximum: 100000, default: 0 },
      },
    },
    responses: {
      BadRequest: {
        description: "The request path or query parameters are invalid.",
        content: { "application/json": { schema: ref("ErrorEnvelope") } },
      },
      Unauthorized: {
        description: "A dedicated Bearer API key is missing or invalid.",
        content: { "application/json": { schema: ref("ErrorEnvelope") } },
      },
      Forbidden: {
        description: "The API key is valid but does not have `institutional:read`.",
        content: { "application/json": { schema: ref("ErrorEnvelope") } },
      },
      Unavailable: {
        description: "No institutional data is available for the requested selector.",
        content: { "application/json": { schema: ref("ErrorEnvelope") } },
      },
      RateLimited: {
        description: "The API client exceeded its configured rate limit.",
        headers: {
          "X-RateLimit-Limit": { $ref: "#/components/headers/X-RateLimit-Limit" },
          "X-RateLimit-Remaining": { $ref: "#/components/headers/X-RateLimit-Remaining" },
          "X-RateLimit-Reset": { $ref: "#/components/headers/X-RateLimit-Reset" },
          "Retry-After": { $ref: "#/components/headers/Retry-After" },
        },
        content: { "application/json": { schema: ref("ErrorEnvelope") } },
      },
      ServerError: {
        description: "Unexpected server failure. Internal details are not returned.",
        content: { "application/json": { schema: ref("ErrorEnvelope") } },
      },
    },
    schemas: {
      Health: {
        type: "object",
        required: ["status", "apiVersion"],
        properties: {
          status: { type: "string", enum: ["ok"] },
          apiVersion: { type: "string", example: "v1" },
        },
      },
      ApiMeta: {
        type: "object",
        required: ["quarter", "dataAsOf", "modelVersion", "source", "requestId", "limitations"],
        properties: {
          quarter: { type: ["string", "null"], pattern: "^\\d{4}-Q[1-4]$" },
          dataAsOf: { type: ["string", "null"], format: "date" },
          modelVersion: { type: "string" },
          source: { type: "string", example: "SEC Form 13F reported holdings" },
          requestId: { type: "string" },
          limitations: { type: "array", items: { type: "string" } },
        },
      },
      SuccessEnvelope: {
        type: "object",
        required: ["data", "meta"],
        properties: {
          data: {},
          meta: ref("ApiMeta"),
        },
      },
      ErrorEnvelope: {
        type: "object",
        required: ["error"],
        properties: {
          error: {
            type: "object",
            required: ["code", "message", "requestId"],
            properties: {
              code: { type: "string", example: "INVALID_QUERY" },
              message: { type: "string" },
              requestId: { type: "string" },
            },
          },
        },
      },
      Quarter: {
        type: "object",
        required: ["year", "quarter", "label", "periodEndDate"],
        properties: {
          year: { type: "integer" },
          quarter: { type: "integer", enum: [1, 2, 3, 4] },
          label: { type: "string", pattern: "^\\d{4}-Q[1-4]$" },
          periodEndDate: { type: "string", format: "date" },
        },
      },
      ModelVersion: {
        type: "object",
        required: ["name", "version"],
        properties: { name: { type: "string" }, version: { type: "string" } },
      },
      DataQuality: {
        type: "object",
        required: ["status", "coveragePercent", "warnings"],
        properties: {
          status: { type: "string", enum: ["complete", "partial", "insufficient", "unavailable"] },
          coveragePercent: { type: ["number", "null"] },
          warnings: { type: "array", items: { type: "string" } },
        },
      },
      ChangeType: {
        type: ["string", "null"],
        enum: ["NEW", "INCREASED", "UNCHANGED", "REDUCED", "EXITED", null],
      },
      FundAllocation: {
        type: "object",
        required: ["name", "reportedValue", "portfolioWeight", "positionCount"],
        properties: {
          name: { type: "string" },
          reportedValue: { type: ["number", "null"] },
          portfolioWeight: { type: ["number", "null"] },
          positionCount: { type: "integer" },
          sector: { type: ["string", "null"] },
          themeId: { type: "string" },
        },
      },
      FundPosition: {
        type: "object",
        required: ["cusip", "symbol", "name", "issuerName", "reportedShares", "reportedValue", "portfolioWeight", "changeType"],
        properties: {
          cusip: { type: "string" },
          symbol: { type: ["string", "null"] },
          name: { type: "string" },
          issuerName: { type: "string" },
          reportedShares: { type: ["number", "null"] },
          reportedValue: { type: ["number", "null"] },
          portfolioWeight: { type: ["number", "null"] },
          previousReportedShares: { type: ["number", "null"] },
          reportedShareChange: { type: ["number", "null"] },
          previousPortfolioWeight: { type: ["number", "null"] },
          portfolioWeightChange: { type: ["number", "null"] },
          changeType: ref("ChangeType"),
          sector: { type: ["string", "null"] },
          industry: { type: ["string", "null"] },
          themeIds: { type: "array", items: { type: "string" } },
          themes: { type: "array", items: { type: "object" } },
        },
      },
      Coverage: {
        type: "object",
        additionalProperties: { type: ["number", "null"] },
      },
      FundAnalytics: {
        type: "object",
        required: ["managerId", "managerName", "quarter", "positionType", "reportedPortfolioValue", "reportedPositionCount", "sectorAllocation", "industryAllocation", "themeAllocation", "largestPortfolioWeights", "dataQuality", "modelVersion"],
        properties: {
          managerId: { type: "string" },
          managerName: { type: ["string", "null"] },
          quarter: ref("Quarter"),
          positionType: { type: "string", enum: ["COMMON_EQUITY", "PUT", "CALL"] },
          reportedPortfolioValue: { type: ["number", "null"] },
          reportedPositionCount: { type: "integer" },
          top5Weight: { type: ["number", "null"] },
          top10Weight: { type: ["number", "null"] },
          top20Weight: { type: ["number", "null"] },
          sectorAllocation: { type: "array", items: ref("FundAllocation") },
          industryAllocation: { type: "array", items: ref("FundAllocation") },
          themeAllocation: { type: "array", items: ref("FundAllocation") },
          newlyReportedCount: { type: "integer" },
          increasedReportedCount: { type: "integer" },
          reducedReportedCount: { type: "integer" },
          noLongerReportedCount: { type: "integer" },
          largestPortfolioWeights: { type: "array", items: ref("FundPosition") },
          largestReportedShareIncreases: { type: "array", items: ref("FundPosition") },
          largestReportedShareReductions: { type: "array", items: ref("FundPosition") },
          largestWeightIncreases: { type: "array", items: ref("FundPosition") },
          largestWeightDecreases: { type: "array", items: ref("FundPosition") },
          mappingCoverage: ref("Coverage"),
          classificationCoverage: ref("Coverage"),
          previousQuarter: { anyOf: [ref("Quarter"), { type: "null" }] },
          dataQuality: ref("DataQuality"),
          modelVersion: ref("ModelVersion"),
        },
      },
      StockHolder: {
        type: "object",
        properties: {
          managerId: { type: "string" },
          managerName: { type: "string" },
          cusip: { type: ["string", "null"] },
          cusips: { type: "array", items: { type: "string" } },
          symbol: { type: "string" },
          issuerName: { type: "string" },
          reportedShares: { type: ["number", "null"] },
          previousReportedShares: { type: ["number", "null"] },
          reportedShareChange: { type: ["number", "null"] },
          reportedShareChangePct: { type: ["number", "null"] },
          reportedValueDollars: { type: ["number", "null"] },
          portfolioWeight: { type: ["number", "null"] },
          changeType: ref("ChangeType"),
        },
      },
      StockAnalytics: {
        type: "object",
        required: ["symbol", "quarter", "dataAsOf", "reportingManagerCount", "reportedHolderCount", "topReportedHolders", "dataQuality", "modelVersion"],
        properties: {
          symbol: { type: "string" },
          quarter: ref("Quarter"),
          dataAsOf: { type: ["string", "null"], format: "date" },
          reportingManagerCount: { type: "integer" },
          reportedHolderCount: { type: "integer" },
          previousReportedHolderCount: { type: ["integer", "null"] },
          holderCountChange: { type: ["integer", "null"] },
          newlyReportedHolderCount: { type: "integer" },
          increasedReportedHolderCount: { type: "integer" },
          unchangedReportedHolderCount: { type: "integer" },
          reducedReportedHolderCount: { type: "integer" },
          noLongerReportedHolderCount: { type: "integer" },
          aggregateReportedShares: { type: ["number", "null"] },
          previousAggregateReportedShares: { type: ["number", "null"] },
          aggregateReportedShareChange: { type: ["number", "null"] },
          aggregateReportedShareChangePct: { type: ["number", "null"] },
          aggregateReportedValueDollars: { type: ["number", "null"] },
          averagePortfolioWeight: { type: ["number", "null"] },
          medianPortfolioWeight: { type: ["number", "null"] },
          topReportedHolders: { type: "array", items: ref("StockHolder") },
          largestNewlyReportedPositions: { type: "array", items: ref("StockHolder") },
          largestReportedShareIncreases: { type: "array", items: ref("StockHolder") },
          largestReportedShareReductions: { type: "array", items: ref("StockHolder") },
          noLongerReportedPositions: { type: "array", items: ref("StockHolder") },
          mappingCoverage: ref("Coverage"),
          managerChangeCounts: { type: "object", additionalProperties: { type: "integer" } },
          breadth: { type: ["object", "null"] },
          trend: { type: ["object", "null"] },
          dataQuality: ref("DataQuality"),
          modelVersion: ref("ModelVersion"),
        },
      },
      StockTrendQuarter: {
        type: "object",
        required: ["quarter", "reportedHolderCount", "hasComparablePriorQuarter"],
        properties: {
          quarter: ref("Quarter"),
          reportedHolderCount: { type: "integer" },
          newlyReportedHolderCount: { type: "integer" },
          increasedReportedHolderCount: { type: "integer" },
          reducedReportedHolderCount: { type: "integer" },
          noLongerReportedHolderCount: { type: "integer" },
          aggregateReportedShares: { type: ["number", "null"] },
          aggregateReportedValue: { type: ["number", "null"] },
          breadthChange: { type: ["number", "null"] },
          shareTrend: { type: ["number", "null"] },
          persistence: { type: ["number", "null"] },
          increaseReductionBalance: { type: ["number", "null"] },
          hasComparablePriorQuarter: { type: "boolean" },
        },
      },
      StockTrend: {
        type: "object",
        required: ["symbol", "quarters", "classification", "dataQuality", "modelVersion"],
        properties: {
          symbol: { type: "string" },
          quarters: { type: "array", items: ref("StockTrendQuarter") },
          classification: { type: "string", enum: ["ACCELERATING_ACCUMULATION", "ACCUMULATION", "STABLE", "DISTRIBUTION", "ACCELERATING_DISTRIBUTION", "INSUFFICIENT_DATA"] },
          dataQuality: ref("DataQuality"),
          modelVersion: ref("ModelVersion"),
        },
      },
      RankingItem: {
        type: "object",
        properties: {
          symbol: { type: "string" },
          companyName: { type: ["string", "null"] },
          sector: { type: ["string", "null"] },
          industry: { type: ["string", "null"] },
          marketCap: { type: ["number", "null"] },
          currentReportedHolderCount: { type: "integer" },
          previousReportedHolderCount: { type: ["integer", "null"] },
          holderCountChange: { type: ["integer", "null"] },
          newlyReportedHolderCount: { type: "integer" },
          increasedReportedHolderCount: { type: "integer" },
          reducedReportedHolderCount: { type: "integer" },
          noLongerReportedHolderCount: { type: "integer" },
          unchangedReportedHolderCount: { type: "integer" },
          netHolderIncrease: { type: ["integer", "null"] },
          aggregateReportedShares: { type: ["number", "null"] },
          previousAggregateReportedShares: { type: ["number", "null"] },
          aggregateReportedShareChange: { type: ["number", "null"] },
          aggregateReportedShareChangePct: { type: ["number", "null"] },
          aggregateReportedValue: { type: ["number", "null"] },
          increaseToReductionRatio: { type: ["number", "null"] },
          cusips: { type: "array", items: { type: "string" } },
        },
      },
      InstitutionalRanking: {
        type: "object",
        required: ["mode", "quarter", "items", "totalCount", "limit", "offset", "dataQuality", "modelVersion"],
        properties: {
          mode: { type: "string", enum: ["ACCUMULATION", "REDUCTION", "NEWLY_REPORTED", "NO_LONGER_REPORTED"] },
          quarter: ref("Quarter"),
          previousQuarter: { anyOf: [ref("Quarter"), { type: "null" }] },
          sortBy: { type: "string" },
          sortDirection: { type: "string", enum: ["asc", "desc"] },
          items: { type: "array", items: ref("RankingItem") },
          totalCount: { type: "integer" },
          limit: { type: "integer" },
          offset: { type: "integer" },
          trackedManagerCount: { type: "integer" },
          comparableManagerCount: { type: "integer" },
          dataQuality: ref("DataQuality"),
          modelVersion: ref("ModelVersion"),
        },
      },
      RotationClassification: {
        type: "object",
        properties: {
          quarter: ref("Quarter"),
          classification: { type: "string" },
          classificationId: { type: "string" },
          currentReportedValue: { type: ["number", "null"] },
          previousReportedValue: { type: ["number", "null"] },
          reportedValueChange: { type: ["number", "null"] },
          reportedValueChangePct: { type: ["number", "null"] },
          currentReportedShares: { type: ["number", "null"] },
          managerCount: { type: "integer" },
          previousManagerCount: { type: ["integer", "null"] },
          managerCountChange: { type: ["integer", "null"] },
          newlyReportedPositionCount: { type: "integer" },
          increasedReportedPositionCount: { type: "integer" },
          reducedReportedPositionCount: { type: "integer" },
          noLongerReportedPositionCount: { type: "integer" },
        },
      },
      Rotation: {
        type: "object",
        required: ["kind", "quarter", "previousQuarter", "classifications", "dataQuality", "modelVersion"],
        properties: {
          kind: { type: "string", enum: ["SECTOR", "INDUSTRY", "THEME"] },
          quarter: ref("Quarter"),
          previousQuarter: { anyOf: [ref("Quarter"), { type: "null" }] },
          classifications: { type: "array", items: ref("RotationClassification") },
          dataQuality: ref("DataQuality"),
          modelVersion: ref("ModelVersion"),
        },
      },
    },
  },
} as const;

export type InstitutionalApiV1OpenApiDocument =
  typeof institutionalApiV1OpenApi;